name = "schawarmatime"
compatibility_date = "2026-05-06"

[build]
command = "npm --prefix ./schawarma-time-app run build"

[assets]
directory = "./schawarma-time-app/dist"
not_found_handling = "single-page-application"
