-- Migration: 008 — RLS Hardening v10
-- Source: security_fixes_v10.sql
-- Fixes:
--   🔴-A: restaurant_settings "Public read settings" USING(TRUE) policy dropped.
--         Replaced with "Staff read settings" USING(has_role(['manager','cashier'])).
--         Public consumers must use the restaurant_info view (created in v9).
--   🟡-A: protect_role_column() trigger — NULL-safe auth.uid() guard added.
--         Handles service-role / unauthenticated call paths without throwing.
-- Frontend: No changes needed — restaurantService.ts already routes:
--   fetchSettings()      → restaurant_info view  (public/customers)
--   fetchSettingsAdmin() → restaurant_settings   (manager JWT only)
-- Applied: via Supabase SQL Editor
-- Status: APPLIED
