-- Migration: 004 — Security fixes v6
-- Source: security_fixes_v6.sql
-- Fixes: postal-code regex (last 5-digit sequence),
--        phone normalization (+49 vs 0049 canonicalization),
--        pgcrypto declared before use,
--        discount cap checked before used_count increment,
--        order_rate_limit_phone table (phone-based rate limiting)
-- Applied: via Supabase Management API
-- Status: APPLIED

-- To apply to a fresh database, run security_fixes_v6.sql in the Supabase SQL Editor.
-- This migration supersedes create_order_secure() from v5.
